//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageTest1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public string NumberOfScreen {
            get {
                return ((string)(this["NumberOfScreen"]));
            }
            set {
                this["NumberOfScreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 960, 540 / 960, 0, 960, 440 / 0, 540, 400, 540")]
        public string ScreenInfomations {
            get {
                return ((string)(this["ScreenInfomations"]));
            }
            set {
                this["ScreenInfomations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.25, 0.5, 0.75, 1.0, 1.5, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0")]
        public string ResizeList {
            get {
                return ((string)(this["ResizeList"]));
            }
            set {
                this["ResizeList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1, 0, 1")]
        public string LeftDestinations {
            get {
                return ((string)(this["LeftDestinations"]));
            }
            set {
                this["LeftDestinations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1, 0, 1")]
        public string RightDestinations {
            get {
                return ((string)(this["RightDestinations"]));
            }
            set {
                this["RightDestinations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2, 2, 0")]
        public string UpDestinations {
            get {
                return ((string)(this["UpDestinations"]));
            }
            set {
                this["UpDestinations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2, 2, 0")]
        public string DownDestinations {
            get {
                return ((string)(this["DownDestinations"]));
            }
            set {
                this["DownDestinations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string HorizontallyLongScreen {
            get {
                return ((string)(this["HorizontallyLongScreen"]));
            }
            set {
                this["HorizontallyLongScreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string VerticallyLongScreen {
            get {
                return ((string)(this["VerticallyLongScreen"]));
            }
            set {
                this["VerticallyLongScreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string Maximize {
            get {
                return ((string)(this["Maximize"]));
            }
            set {
                this["Maximize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string MoveValueSmall {
            get {
                return ((string)(this["MoveValueSmall"]));
            }
            set {
                this["MoveValueSmall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32")]
        public string MoveValueLarge {
            get {
                return ((string)(this["MoveValueLarge"]));
            }
            set {
                this["MoveValueLarge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CommandLine {
            get {
                return ((string)(this["CommandLine"]));
            }
            set {
                this["CommandLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string BorderWidth {
            get {
                return ((string)(this["BorderWidth"]));
            }
            set {
                this["BorderWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string PreLoadNumber {
            get {
                return ((string)(this["PreLoadNumber"]));
            }
            set {
                this["PreLoadNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string MaxThreads {
            get {
                return ((string)(this["MaxThreads"]));
            }
            set {
                this["MaxThreads"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string InterpolationMode {
            get {
                return ((string)(this["InterpolationMode"]));
            }
            set {
                this["InterpolationMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public string BufferNumber {
            get {
                return ((string)(this["BufferNumber"]));
            }
            set {
                this["BufferNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string ScreenInfoAuto {
            get {
                return ((string)(this["ScreenInfoAuto"]));
            }
            set {
                this["ScreenInfoAuto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public string InterlockScreenNumber {
            get {
                return ((string)(this["InterlockScreenNumber"]));
            }
            set {
                this["InterlockScreenNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string MoveAfterCopy {
            get {
                return ((string)(this["MoveAfterCopy"]));
            }
            set {
                this["MoveAfterCopy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string ChangeLeftRight {
            get {
                return ((string)(this["ChangeLeftRight"]));
            }
            set {
                this["ChangeLeftRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("x")]
        public string DoMaximize {
            get {
                return ((string)(this["DoMaximize"]));
            }
            set {
                this["DoMaximize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("f")]
        public string DoRotateRight {
            get {
                return ((string)(this["DoRotateRight"]));
            }
            set {
                this["DoRotateRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d")]
        public string DoRotateLeft {
            get {
                return ((string)(this["DoRotateLeft"]));
            }
            set {
                this["DoRotateLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+")]
        public string DoExpansion {
            get {
                return ((string)(this["DoExpansion"]));
            }
            set {
                this["DoExpansion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-")]
        public string DoReduce {
            get {
                return ((string)(this["DoReduce"]));
            }
            set {
                this["DoReduce"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("q,Up")]
        public string DoPrevFile {
            get {
                return ((string)(this["DoPrevFile"]));
            }
            set {
                this["DoPrevFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("a,Down")]
        public string DoNextFile {
            get {
                return ((string)(this["DoNextFile"]));
            }
            set {
                this["DoNextFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Left")]
        public string DoPrevFileChangable {
            get {
                return ((string)(this["DoPrevFileChangable"]));
            }
            set {
                this["DoPrevFileChangable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Right")]
        public string DoNextFileChangable {
            get {
                return ((string)(this["DoNextFileChangable"]));
            }
            set {
                this["DoNextFileChangable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+Left")]
        public string DoMoveLeftSmall {
            get {
                return ((string)(this["DoMoveLeftSmall"]));
            }
            set {
                this["DoMoveLeftSmall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+Right")]
        public string DoMoveRightSmall {
            get {
                return ((string)(this["DoMoveRightSmall"]));
            }
            set {
                this["DoMoveRightSmall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+Up")]
        public string DoMoveUpSmall {
            get {
                return ((string)(this["DoMoveUpSmall"]));
            }
            set {
                this["DoMoveUpSmall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+Down")]
        public string DoMoveDownSmall {
            get {
                return ((string)(this["DoMoveDownSmall"]));
            }
            set {
                this["DoMoveDownSmall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+Left")]
        public string DoMoveLeftLarge {
            get {
                return ((string)(this["DoMoveLeftLarge"]));
            }
            set {
                this["DoMoveLeftLarge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+Right")]
        public string DoMoveRightLarge {
            get {
                return ((string)(this["DoMoveRightLarge"]));
            }
            set {
                this["DoMoveRightLarge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+Up")]
        public string DoMoveUpLarge {
            get {
                return ((string)(this["DoMoveUpLarge"]));
            }
            set {
                this["DoMoveUpLarge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+Down")]
        public string DoMoveDownLarge {
            get {
                return ((string)(this["DoMoveDownLarge"]));
            }
            set {
                this["DoMoveDownLarge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+Left")]
        public string DoMoveLeftScreen {
            get {
                return ((string)(this["DoMoveLeftScreen"]));
            }
            set {
                this["DoMoveLeftScreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+Right")]
        public string DoMoveRightScreen {
            get {
                return ((string)(this["DoMoveRightScreen"]));
            }
            set {
                this["DoMoveRightScreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+Up")]
        public string DoMoveUpScreen {
            get {
                return ((string)(this["DoMoveUpScreen"]));
            }
            set {
                this["DoMoveUpScreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+Down")]
        public string DoMoveDownScreen {
            get {
                return ((string)(this["DoMoveDownScreen"]));
            }
            set {
                this["DoMoveDownScreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NumPad0")]
        public string DoNoCopyFile {
            get {
                return ((string)(this["DoNoCopyFile"]));
            }
            set {
                this["DoNoCopyFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Decimal")]
        public string DoNoCopyFileReverse {
            get {
                return ((string)(this["DoNoCopyFileReverse"]));
            }
            set {
                this["DoNoCopyFileReverse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NumPad1")]
        public string DoCopyFile1 {
            get {
                return ((string)(this["DoCopyFile1"]));
            }
            set {
                this["DoCopyFile1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NumPad2")]
        public string DoCopyFile2 {
            get {
                return ((string)(this["DoCopyFile2"]));
            }
            set {
                this["DoCopyFile2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NumPad3")]
        public string DoCopyFile3 {
            get {
                return ((string)(this["DoCopyFile3"]));
            }
            set {
                this["DoCopyFile3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NumPad4")]
        public string DoCopyFile4 {
            get {
                return ((string)(this["DoCopyFile4"]));
            }
            set {
                this["DoCopyFile4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NumPad5")]
        public string DoCopyFile5 {
            get {
                return ((string)(this["DoCopyFile5"]));
            }
            set {
                this["DoCopyFile5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NumPad6")]
        public string DoCopyFile6 {
            get {
                return ((string)(this["DoCopyFile6"]));
            }
            set {
                this["DoCopyFile6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NumPad7")]
        public string DoCopyFile7 {
            get {
                return ((string)(this["DoCopyFile7"]));
            }
            set {
                this["DoCopyFile7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NumPad8")]
        public string DoCopyFile8 {
            get {
                return ((string)(this["DoCopyFile8"]));
            }
            set {
                this["DoCopyFile8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NumPad9")]
        public string DoCopyFile9 {
            get {
                return ((string)(this["DoCopyFile9"]));
            }
            set {
                this["DoCopyFile9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Esc")]
        public string DoClose {
            get {
                return ((string)(this["DoClose"]));
            }
            set {
                this["DoClose"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+F1")]
        public string DoSortModeFilenameAsc {
            get {
                return ((string)(this["DoSortModeFilenameAsc"]));
            }
            set {
                this["DoSortModeFilenameAsc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+F2")]
        public string DoSortModeFilenameDesc {
            get {
                return ((string)(this["DoSortModeFilenameDesc"]));
            }
            set {
                this["DoSortModeFilenameDesc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+F3")]
        public string DoSortModeTimeAsc {
            get {
                return ((string)(this["DoSortModeTimeAsc"]));
            }
            set {
                this["DoSortModeTimeAsc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+F4")]
        public string DoSortModeTimeDesc {
            get {
                return ((string)(this["DoSortModeTimeDesc"]));
            }
            set {
                this["DoSortModeTimeDesc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Home")]
        public string DoFirstFile {
            get {
                return ((string)(this["DoFirstFile"]));
            }
            set {
                this["DoFirstFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("End")]
        public string DoLastFile {
            get {
                return ((string)(this["DoLastFile"]));
            }
            set {
                this["DoLastFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PageDown")]
        public string DoSkipNextFile {
            get {
                return ((string)(this["DoSkipNextFile"]));
            }
            set {
                this["DoSkipNextFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PageUp")]
        public string DoSkipPrevFile {
            get {
                return ((string)(this["DoSkipPrevFile"]));
            }
            set {
                this["DoSkipPrevFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("]")]
        public string DoIncrementPageNumber {
            get {
                return ((string)(this["DoIncrementPageNumber"]));
            }
            set {
                this["DoIncrementPageNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[")]
        public string DoDecrementPageNumber {
            get {
                return ((string)(this["DoDecrementPageNumber"]));
            }
            set {
                this["DoDecrementPageNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("z")]
        public string DoMaximizeModeChange {
            get {
                return ((string)(this["DoMaximizeModeChange"]));
            }
            set {
                this["DoMaximizeModeChange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+C")]
        public string DoCopyFullName {
            get {
                return ((string)(this["DoCopyFullName"]));
            }
            set {
                this["DoCopyFullName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+C")]
        public string DoCopyFile {
            get {
                return ((string)(this["DoCopyFile"]));
            }
            set {
                this["DoCopyFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+Enter")]
        public string DoSelectExplorer {
            get {
                return ((string)(this["DoSelectExplorer"]));
            }
            set {
                this["DoSelectExplorer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter")]
        public string DoExecCommand1 {
            get {
                return ((string)(this["DoExecCommand1"]));
            }
            set {
                this["DoExecCommand1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+F12")]
        public string DoExecCommand2 {
            get {
                return ((string)(this["DoExecCommand2"]));
            }
            set {
                this["DoExecCommand2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+F11")]
        public string DoExecCommand3 {
            get {
                return ((string)(this["DoExecCommand3"]));
            }
            set {
                this["DoExecCommand3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+F10")]
        public string DoExecCommand4 {
            get {
                return ((string)(this["DoExecCommand4"]));
            }
            set {
                this["DoExecCommand4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+F9")]
        public string DoExecCommand5 {
            get {
                return ((string)(this["DoExecCommand5"]));
            }
            set {
                this["DoExecCommand5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F5")]
        public string DoReload {
            get {
                return ((string)(this["DoReload"]));
            }
            set {
                this["DoReload"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string DoSinglePage {
            get {
                return ((string)(this["DoSinglePage"]));
            }
            set {
                this["DoSinglePage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string DoTwoPages {
            get {
                return ((string)(this["DoTwoPages"]));
            }
            set {
                this["DoTwoPages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+I")]
        public string DoInterlock {
            get {
                return ((string)(this["DoInterlock"]));
            }
            set {
                this["DoInterlock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+M")]
        public string DoMoveFiles {
            get {
                return ((string)(this["DoMoveFiles"]));
            }
            set {
                this["DoMoveFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+P")]
        public string DoRenamePage {
            get {
                return ((string)(this["DoRenamePage"]));
            }
            set {
                this["DoRenamePage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("p")]
        public string DoShowPage {
            get {
                return ((string)(this["DoShowPage"]));
            }
            set {
                this["DoShowPage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public string DoThreePages {
            get {
                return ((string)(this["DoThreePages"]));
            }
            set {
                this["DoThreePages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+W")]
        public string DoWatchMode {
            get {
                return ((string)(this["DoWatchMode"]));
            }
            set {
                this["DoWatchMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("o,Ctrl+O")]
        public string DoOpenFile {
            get {
                return ((string)(this["DoOpenFile"]));
            }
            set {
                this["DoOpenFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+O")]
        public string DoOpenDirectory {
            get {
                return ((string)(this["DoOpenDirectory"]));
            }
            set {
                this["DoOpenDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F6")]
        public string DoChangeFocus {
            get {
                return ((string)(this["DoChangeFocus"]));
            }
            set {
                this["DoChangeFocus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public string DoFrontBack {
            get {
                return ((string)(this["DoFrontBack"]));
            }
            set {
                this["DoFrontBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("b")]
        public string DoShowBorder {
            get {
                return ((string)(this["DoShowBorder"]));
            }
            set {
                this["DoShowBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+R")]
        public string DoChangeLeftRight {
            get {
                return ((string)(this["DoChangeLeftRight"]));
            }
            set {
                this["DoChangeLeftRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public string DoTwoPagesFrontBack {
            get {
                return ((string)(this["DoTwoPagesFrontBack"]));
            }
            set {
                this["DoTwoPagesFrontBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@")]
        public string DoConfig {
            get {
                return ((string)(this["DoConfig"]));
            }
            set {
                this["DoConfig"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\fav\\dir1")]
        public string DestinationDirectory1 {
            get {
                return ((string)(this["DestinationDirectory1"]));
            }
            set {
                this["DestinationDirectory1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\fav\\dir2")]
        public string DestinationDirectory2 {
            get {
                return ((string)(this["DestinationDirectory2"]));
            }
            set {
                this["DestinationDirectory2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\fav\\dir3")]
        public string DestinationDirectory3 {
            get {
                return ((string)(this["DestinationDirectory3"]));
            }
            set {
                this["DestinationDirectory3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\fav\\dir4")]
        public string DestinationDirectory4 {
            get {
                return ((string)(this["DestinationDirectory4"]));
            }
            set {
                this["DestinationDirectory4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\fav\\dir5")]
        public string DestinationDirectory5 {
            get {
                return ((string)(this["DestinationDirectory5"]));
            }
            set {
                this["DestinationDirectory5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DestinationDirectory6 {
            get {
                return ((string)(this["DestinationDirectory6"]));
            }
            set {
                this["DestinationDirectory6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DestinationDirectory7 {
            get {
                return ((string)(this["DestinationDirectory7"]));
            }
            set {
                this["DestinationDirectory7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DestinationDirectory8 {
            get {
                return ((string)(this["DestinationDirectory8"]));
            }
            set {
                this["DestinationDirectory8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DestinationDirectory9 {
            get {
                return ((string)(this["DestinationDirectory9"]));
            }
            set {
                this["DestinationDirectory9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string ClearAfterExecCommand1 {
            get {
                return ((string)(this["ClearAfterExecCommand1"]));
            }
            set {
                this["ClearAfterExecCommand1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string ClearAfterExecCommand2 {
            get {
                return ((string)(this["ClearAfterExecCommand2"]));
            }
            set {
                this["ClearAfterExecCommand2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExecCommand3 {
            get {
                return ((string)(this["ExecCommand3"]));
            }
            set {
                this["ExecCommand3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string ClearAfterExecCommand3 {
            get {
                return ((string)(this["ClearAfterExecCommand3"]));
            }
            set {
                this["ClearAfterExecCommand3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExecCommand4 {
            get {
                return ((string)(this["ExecCommand4"]));
            }
            set {
                this["ExecCommand4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string ClearAfterExecCommand4 {
            get {
                return ((string)(this["ClearAfterExecCommand4"]));
            }
            set {
                this["ClearAfterExecCommand4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExecCommand5 {
            get {
                return ((string)(this["ExecCommand5"]));
            }
            set {
                this["ExecCommand5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string ClearAfterExecCommand5 {
            get {
                return ((string)(this["ClearAfterExecCommand5"]));
            }
            set {
                this["ClearAfterExecCommand5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\scan")]
        public string InterlockFolder {
            get {
                return ((string)(this["InterlockFolder"]));
            }
            set {
                this["InterlockFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{MyPictures}")]
        public string InitialFolder {
            get {
                return ((string)(this["InitialFolder"]));
            }
            set {
                this["InitialFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{ImageTest1} -p2 -b -spn {destDir}")]
        public string ExecCommandAfterMoveFiles {
            get {
                return ((string)(this["ExecCommandAfterMoveFiles"]));
            }
            set {
                this["ExecCommandAfterMoveFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"{ImageTest1-Dir}\\ScanClick.ahk\"")]
        public string ExecCommand1 {
            get {
                return ((string)(this["ExecCommand1"]));
            }
            set {
                this["ExecCommand1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"{ImageTest1-Dir}\\RenScan.bat\" {filename}")]
        public string ExecCommand2 {
            get {
                return ((string)(this["ExecCommand2"]));
            }
            set {
                this["ExecCommand2"] = value;
            }
        }
    }
}
